[project]
name = "config_resolver"
version = "0.1.0"
description = ""
authors = [
    {name = "Grigori Kartashyan",email = "grigori.kartashyan@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
