name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        question: [question1, question2]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run tests in container
        run: make test
        working-directory: ${{ matrix.question }}
